apiVersion: v1
kind: ConfigMap
metadata:
  name: cookbook-config
  namespace: cookbook
data:
  ASPNETCORE_ENVIRONMENT: Production
  ApiService__BaseUrl: http://cookbook-api
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  AzureAd__Instance: "https://ultimatecookbook.ciamlogin.com/"
  AzureAd__CallbackPath: "/signin-oidc"
  AzureAd__SignedOutCallbackPath: "/signout-oidc"
