apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cookbook-ingress
  namespace: cookbook
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "blazor-affinity"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/grafana($|/) {
        access_by_lua_block {
          local http = require "resty.http"
          local httpc = http.new()
          httpc:set_timeout(1000)
          local res, err = httpc:request_uri("http://cookbook-api:80/api/v1/metrics/track-dashboard-view", {
            method = "GET",
            connect_timeout = 100,
            read_timeout = 100
          })
          if err then
            ngx.log(ngx.ERR, "Failed to track dashboard view: " .. err)
          end
        }
      }
spec:
  ingressClassName: nginx
  rules:
  - host: cookbook.bencampus.duckdns.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cookbook-api
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cookbook-web
            port:
              number: 80
  - host: cookbook.benhhome.duckdns.org
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cookbook-api
            port:
              number: 80
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cookbook-web
            port:
              number: 80

