apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: cookbook
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          args: ["-config.file=/etc/loki/loki.yaml"]
          ports:
            - containerPort: 3100
          # Probes (readiness/liveness)
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-config
          configMap:
            name: loki-config
