apiVersion: v1
kind: Secret
metadata:
  name: cookbook-secrets
  namespace: cookbook
type: Opaque
stringData:
  ConnectionStrings__sqldb: "Server=<sql-host>;Database=Cookbook;User Id=<user>;Password=<password>;TrustServerCertificate=True"
