apiVersion: v1
kind: Secret
metadata:
  name: cookbook-secrets
  namespace: cookbook
type: Opaque
stringData:
  ConnectionStrings__sqldb: "Server=tcp:sql-cookbook-mc.database.windows.net,1433;Initial Catalog=cookbookDB;User ID=cookbookadmin;Password=#Foodisgood;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  AZURE_AD_TENANT_ID: ""
  AZURE_AD_CLIENT_ID: ""
  AZURE_AD_CLIENT_SECRET: ""
