// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Cookbook.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cookbook.ApiService.Data.Migrations
{
    [DbContext(typeof(CookbookDbContext))]
    [Migration("20260410000000_AddUserProfiles")]
    partial class AddUserProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cookbook.ApiService.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("Cookbook.ApiService.Models.BoardPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BoardId", "UserId")
                        .IsUnique();

                    b.ToTable("BoardPermissions", (string)null);
                });

            modelBuilder.Entity("Cookbook.ApiService.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CookTime")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CookingTemperature")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<List<string>>("Equipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasConversion(
                            new ValueConverter<List<string>, string>(
                                v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
                                v => string.IsNullOrWhiteSpace(v)
                                    ? new List<string>()
                                    : JsonSerializer.Deserialize<List<string>>(v) ?? new List<string>()),
                            new ValueComparer<List<string>>(
                                (l, r) => l == null && r == null || l != null && r != null && l.SequenceEqual(r),
                                v => v == null ? 0 : v.Aggregate(0, (c, i) => HashCode.Combine(c, i == null ? 0 : i.GetHashCode())),
                                v => v == null ? new List<string>() : v.ToList()));

                    b.Property<List<string>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasConversion(
                            new ValueConverter<List<string>, string>(
                                v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
                                v => string.IsNullOrWhiteSpace(v)
                                    ? new List<string>()
                                    : JsonSerializer.Deserialize<List<string>>(v) ?? new List<string>()),
                            new ValueComparer<List<string>>(
                                (l, r) => l == null && r == null || l != null && r != null && l.SequenceEqual(r),
                                v => v == null ? 0 : v.Aggregate(0, (c, i) => HashCode.Combine(c, i == null ? 0 : i.GetHashCode())),
                                v => v == null ? new List<string>() : v.ToList()));

                    b.Property<List<string>>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasConversion(
                            new ValueConverter<List<string>, string>(
                                v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
                                v => string.IsNullOrWhiteSpace(v)
                                    ? new List<string>()
                                    : JsonSerializer.Deserialize<List<string>>(v) ?? new List<string>()),
                            new ValueComparer<List<string>>(
                                (l, r) => l == null && r == null || l != null && r != null && l.SequenceEqual(r),
                                v => v == null ? 0 : v.Aggregate(0, (c, i) => HashCode.Combine(c, i == null ? 0 : i.GetHashCode())),
                                v => v == null ? new List<string>() : v.ToList()));

                    b.Property<string>("NutritionFacts")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PrepTime")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<List<string>>("Quantities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasConversion(
                            new ValueConverter<List<string>, string>(
                                v => JsonSerializer.Serialize(v, (JsonSerializerOptions)null),
                                v => string.IsNullOrWhiteSpace(v)
                                    ? new List<string>()
                                    : JsonSerializer.Deserialize<List<string>>(v) ?? new List<string>()),
                            new ValueComparer<List<string>>(
                                (l, r) => l == null && r == null || l != null && r != null && l.SequenceEqual(r),
                                v => v == null ? 0 : v.Aggregate(0, (c, i) => HashCode.Combine(c, i == null ? 0 : i.GetHashCode())),
                                v => v == null ? new List<string>() : v.ToList()));

                    b.Property<string>("StorageInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TotalTime")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("YieldServings")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("Cookbook.ApiService.Models.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Cookbook.ApiService.Models.BoardPermission", b =>
                {
                    b.HasOne("Cookbook.ApiService.Models.Board", "Board")
                        .WithMany("Permissions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("Cookbook.ApiService.Models.Board", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
