# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - cookbookwebapp

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/Directory.Packages.props
            **/NuGet.config
            **/global.json

      - name: Restore ApiService
        run: dotnet restore Cookbook.ApiService/Cookbook.ApiService.csproj

      - name: Restore Web App
        run: dotnet restore CookbookMauiBlazor/CookbookMauiBlazor.Web/CookbookMauiBlazor.Web.csproj

      - name: Build ApiService
        run: dotnet build Cookbook.ApiService/Cookbook.ApiService.csproj --configuration Release --no-restore

      - name: Build Web App
        run: dotnet build CookbookMauiBlazor/CookbookMauiBlazor.Web/CookbookMauiBlazor.Web.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish CookbookMauiBlazor/CookbookMauiBlazor.Web/CookbookMauiBlazor.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C69BC55505754472902A6F806EDDB0FB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C84A6F3413BE46779C694B332A018107 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0730FF961B8F49D989FF96D600AF2FA9}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "cookbookwebapp"
          slot-name: "Production"
          package: .
